### ISSUE TITLE
 RunTimeError:NotImplementedError

### ISSUE THREAD

**Issue by aaronliu7** [ChangyWen/wolpertinger_ddpg#1]
I got an RunTimeError:NotImplementedError in ActionWrapper.step while training with gym, and I replace my gym/core.py file with core.py in openai/gym. But it still has NotImplementedError on core.py. I don't know why.

**Comment by Thanksyy** [comment]
Hi, I also meet the same problem as the aaronliu7. I have tried several alternative methods, but they didn't work.

**Comment by Mikey2266** [comment]
Have you solved this problem?

**Comment by aaronliu7** [comment]
> Have you solved this problem?

Maybe the gym version is too high. Downgrade your gym version or try gym v0.14.0, it works for me.

**Comment by Mikey2266** [comment]
OK!!Thanks!!
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aaronliu7"<notifications@github.com&gt;; 
发送时间: 2020年5月22日(星期五) 上午10:48
收件人: "ChangyWen/wolpertinger_ddpg"<wolpertinger_ddpg@noreply.github.com&gt;; 
抄送: "沉默的23点"<601876177@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ChangyWen/wolpertinger_ddpg]  RunTimeError:NotImplementedError (#1)





  
Have you solved this problem?
  
Maybe the gym version is too high. Downgrade your gym version or try gym v0.14.0, it works for me.

**Comment by ChangyWen** [comment]
@aaronliu7 thanks for your help.
